#! /usr/bin/env python
#
# Print experiment info in shell-digestible form
#
# $Id: getexp 3740 2014-10-17 12:39:49Z m221078 $
#

import argparse
import os
import sys

from expconfig import ExpConfig, ExpConfigError
from feedback import die

# Basic settings


#
# Main routine
#

# Check environment

config_roots = os.environ.get('MKEXP_PATH', '').split(':')

# Check command line

command_line = argparse.ArgumentParser(description=
    'Generate an experiment from templates and the given configuration file.')
command_line.add_argument('config', help='experiment configuration file name')
command_line.add_argument('assigns', metavar='key=value', nargs='*',
                           help='override configuration file settings')
command_line.add_argument('--path', '-p', 
                          help='search path for default config and templates')
command_line.add_argument('--verbose', '-v', action='store_true',
                          help='show additional information')

args = command_line.parse_args()

# Experiment configuration
if args.path:
    config_roots = args.path.split(':')

experiment_config_name = args.config

if not os.path.exists(experiment_config_name):
    die("config file '{0}' does not exist".format(experiment_config_name))

# Overrides
invalid_args = filter(lambda x: not x.find('=')+1, args.assigns)

if invalid_args:
    die("invalid parameters ('"+"', '".join(invalid_args)+"')\n" +
        command_line.format_usage())

# Read and store configuration info from input and experiments' library
# Store environment as default for control settings, then add config from files

# Hack to allow use in diffexp
if os.environ.has_key('DIFF'):
    del os.environ['DIFF']

try:
    config = ExpConfig(experiment_config_name,
                       dict(map(lambda x: x.split('=', 1), args.assigns)),
                       config_roots)
except ExpConfigError as error:
    die(error.message, status=2)

if args.verbose:
    items = config.items()
    items.sort(key=lambda x: x[0])
    for (key, value) in items:
        if not isinstance(value, dict):
            print("{0}='{1}'".format(key, value))
else:
    print("EXP_ID='{0}'".format(config.experiment_id))
    print("MODEL_DIR='{0}'".format(config['MODEL_DIR']))
    print("SCRIPT_DIR='{0}'".format(config['SCRIPT_DIR']))
    print("WORK_DIR='{0}'".format(config['WORK_DIR']))
    print("DATA_DIR='{0}'".format(config['DATA_DIR']))

if not (os.path.isdir(config['MODEL_DIR']) and
        os.path.isdir(config['SCRIPT_DIR']) and
        os.path.isdir(config['WORK_DIR']) and
        os.path.isdir(config['DATA_DIR'])):
    die("data for experiment '{0}' does not exist".format(config.experiment_id))

