#! /usr/bin/perl
#
# Copyright  (C)  2015  Luis Kornblueh <luis.kornblueh@mpimet.mpg.de>
#
# Version: 1.0
#
# Author: Luis Kornblueh <luis.kornblueh@mpimet.mpg.de>
# Maintainer: Luis Kornblueh <luis.kornblueh@mpimet.mpg.de>
#
# Redistribution and use in source and binary forms, with or without
# modification, are  permitted provided that the following conditions are
# met:
#
# Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# Neither the name of the DKRZ GmbH nor the names of its contributors
# may be used to endorse or promote products derived from this software
# without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
# PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# Fix problems with starting mvapich2 local on SMP node (no CMA available)
#
use strict;
use warnings;

use File::Spec::Functions qw(catfile);

my $mpiexec = catfile($ENV{'MPIROOT'}, 'bin/mpiexec');

if ( -x $mpiexec) {
  # invoke real mpiexec with all arguments

  print @ARGV;  

  $ENV{'MV2_SMP_USE_CMA'}=0;
  exec($mpiexec, @ARGV)
    or die('exec failed', "\n");

} else {

  die('No mpiexec to invoke found!', "\n");

}



