!*    NAMELIST *FIRE_JSBACH_CTL* To control JSBACH vegetation disturbance algorithms.
!                                                                 
!      
!      NAME                TYPE       PURPOSE                                       
!      ----                ----       -------                                       
!
!     *FIRE_LITTER_        REAL       minimal amount of litter [mol(C)/m^2(grid box)] for fire
!      THRESHOLD*
!     *FIRE_REL_HUM_       REAL       maximal relative humidity for fire
!      THRESHOLD*          
!     *FIRE_MINIMUM_WOODY* REAL       minimal fraction of act_fpc of woody PFT to be burned each year
!     *FIRE_MINIMUM_GRASS* REAL       minimal fraction of act_fpc of grass PFT to be burned each year
!     *FIRE_TAU_WOODY*     REAL       return period of fire for woody PFT [year] at 0 % relative humidity
!     *FIRE_TAU_GRASS*     REAL       return period of fire for grass PFT [year] at 0 % relative humidity
!

NAMELIST /FIRE_JSBACH_CTL/                                                              &
 fire_litter_threshold, fire_rel_hum_threshold, fire_minimum_woody, fire_minimum_grass, & ! JSBACH fire
 fire_tau_woody, fire_tau_grass                                                           ! JSBACH fire
!     ------------------------------------------------------------------
