!------------------------------------------------------------------------------
!
! hratesctl.inc
! 
!------------------------------------------------------------------------------
!
! variable name   & description & default \\
!
!------------------------------------------------------------------------------
NAMELIST /hratesctl/ &
  puthrates          ! output frequency of heating rates, default = trigrad
